# Generated by Django 4.2.7 on 2024-03-06 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название привычки')),
                ('place', models.CharField(max_length=200, verbose_name='место')),
                ('time', models.TimeField(verbose_name='время выполнения')),
                ('action', models.TextField(verbose_name='действие')),
                ('nice_habit', models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак привычки')),
                ('periodicity', models.CharField(choices=[('Раз в час', 'Раз в час'), ('Раз в неделю', 'Раз в неделю'), ('РАз в месяц', 'Раз в месяц')], max_length=20, verbose_name='переодичность')),
                ('reward', models.TextField(verbose_name='вознаграждение')),
                ('time_to_complete', models.SmallIntegerField(verbose_name='время на выполнение')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликованно')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_habit', to='habits.goodhabit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
