# Generated by Django 4.2.7 on 2024-03-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodhabit',
            name='reward',
            field=models.TextField(blank=True, null=True, verbose_name='вознаграждение'),
        ),
    ]
