# Generated by Django 4.2.7 on 2024-03-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_goodhabit_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodhabit',
            name='periodicity',
            field=models.CharField(choices=[('Раз в час', 'Раз в час'), ('Раз в день', 'Раз в день'), ('РАз в неделю', 'Раз в неделю')], max_length=20, verbose_name='переодичность'),
        ),
    ]
