# Generated by Django 4.2.7 on 2024-03-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_goodhabit_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodhabit',
            name='periodicity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='переодичность'),
        ),
    ]
