# Generated by Django 4.2.7 on 2024-03-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_goodhabit_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodhabit',
            old_name='date_created',
            new_name='date_of_completion',
        ),
    ]
